name: Dockeer

on:
  workflow_call:

jobs:
  
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup DOcker Build
      uses: docker/setup-buildx-action@v2.4.1
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
    # Username used to log against the Docker registry
        username: xsully
    # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASS }}